#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBCE5DC3C741A02D1 (david.oberhollenzer@sigma-star.at)
#
Name     : mtd-utils
Version  : 2.0.2
Release  : 2
URL      : ftp://ftp.infradead.org/pub/mtd-utils/mtd-utils-2.0.2.tar.bz2
Source0  : ftp://ftp.infradead.org/pub/mtd-utils/mtd-utils-2.0.2.tar.bz2
Source99 : ftp://ftp.infradead.org/pub/mtd-utils/mtd-utils-2.0.2.tar.bz2.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: mtd-utils-bin = %{version}-%{release}
Requires: mtd-utils-license = %{version}-%{release}
Requires: mtd-utils-man = %{version}-%{release}
BuildRequires : acl-dev
BuildRequires : lzo-dev
BuildRequires : pkgconfig(cmocka)
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(zlib)

%description
UBIFS File System - Make File System program
* crc16.h and crc16.c were copied from the linux kernel.
* crc32.h and crc32.c were copied from mtd-utils and amended.
* ubifs.h is a selection of definitions from fs/ubifs/ubifs.h from the linux kernel.
* key.h is copied from fs/ubifs/key.h from the linux kernel.
* defs.h is a bunch of definitions to smooth things over.
* lpt.c is a selection of functions copied from fs/ubifs/lpt.c from the linux kernel, and amended.
* hashtable/* was downloaded from http://www.cl.cam.ac.uk/~cwc22/hashtable/

%package bin
Summary: bin components for the mtd-utils package.
Group: Binaries
Requires: mtd-utils-license = %{version}-%{release}
Requires: mtd-utils-man = %{version}-%{release}

%description bin
bin components for the mtd-utils package.


%package license
Summary: license components for the mtd-utils package.
Group: Default

%description license
license components for the mtd-utils package.


%package man
Summary: man components for the mtd-utils package.
Group: Default

%description man
man components for the mtd-utils package.


%prep
%setup -q -n mtd-utils-2.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542909832
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1542909832
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mtd-utils
cp COPYING %{buildroot}/usr/share/package-licenses/mtd-utils/COPYING
cp lib/LICENSE.libiniparser %{buildroot}/usr/share/package-licenses/mtd-utils/lib_LICENSE.libiniparser
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/doc_loadbios
/usr/bin/docfdisk
/usr/bin/flash_erase
/usr/bin/flash_eraseall
/usr/bin/flash_lock
/usr/bin/flash_otp_dump
/usr/bin/flash_otp_info
/usr/bin/flash_otp_lock
/usr/bin/flash_otp_write
/usr/bin/flash_unlock
/usr/bin/flashcp
/usr/bin/ftl_check
/usr/bin/ftl_format
/usr/bin/jffs2dump
/usr/bin/jffs2reader
/usr/bin/mkfs.jffs2
/usr/bin/mkfs.ubifs
/usr/bin/mtd_debug
/usr/bin/mtdinfo
/usr/bin/mtdpart
/usr/bin/nanddump
/usr/bin/nandtest
/usr/bin/nandwrite
/usr/bin/nftl_format
/usr/bin/nftldump
/usr/bin/recv_image
/usr/bin/rfddump
/usr/bin/rfdformat
/usr/bin/serve_image
/usr/bin/sumtool
/usr/bin/ubiattach
/usr/bin/ubiblock
/usr/bin/ubicrc32
/usr/bin/ubidetach
/usr/bin/ubiformat
/usr/bin/ubimkvol
/usr/bin/ubinfo
/usr/bin/ubinize
/usr/bin/ubirename
/usr/bin/ubirmvol
/usr/bin/ubirsvol
/usr/bin/ubiupdatevol

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mtd-utils/COPYING
/usr/share/package-licenses/mtd-utils/lib_LICENSE.libiniparser

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mkfs.jffs2.1
/usr/share/man/man8/ubinize.8
